react-component/picker

tests/generate.spec.tsx

test: Add generate test case

---

src/PickerPanel.tsx
src/panels/YearPanel/index.tsx
tests/picker.spec.tsx

feat: Year panel record source mode

---

src/generate/moment.ts
tests/generate.spec.tsx

fix https://github.com/ant-design/ant-design/issues/20799

fix: Generate should not change value immutable data

---

src/hooks/usePickerInput.ts
tests/keyboard.spec.tsx

fix https://github.com/ant-design/ant-design/issues/21181

fix: Picker input should not trigger form submit

---

src/PickerPanel.tsx
src/interface.ts
src/panels/DatePanel/index.tsx
src/panels/DecadePanel/index.tsx
src/panels/MonthPanel/index.tsx
src/panels/YearPanel/index.tsx
tests/picker.spec.tsx

ref https://github.com/ant-design/ant-design/issues/21287
Should release `1.0.0` after merge

feat: `onPanelChange` also trigger when panel switch

---

src/locale/pt_BR.ts

Change translation string "tempo" to "hora" on portuguese language.

fix(locale): Update time string pt_BR translation

---

src/Picker.tsx
src/RangePicker.tsx
src/hooks/useValueTexts.ts
tests/picker.spec.tsx

fix https://github.com/ant-design/ant-design/issues/21553

Reset input value when Picker close

---

package.json
src/Picker.tsx
src/hooks/useValueTexts.ts
tests/picker.spec.tsx

fix https://github.com/ant-design/ant-design/issues/21856

fix: Update display value when picker changed

---

src/Picker.tsx
src/RangePicker.tsx
tests/setup.js

fix https://github.com/ant-design/ant-design/issues/21995

fix: Clear to open the panel

---

src/RangePicker.tsx

resolve https://github.com/ant-design/ant-design/issues/22158

export activePicker

---

src/generate/moment.ts
src/utils/dateUtil.ts
tests/util.spec.tsx

Ref: ant-design/ant-design#21906

fix ant-design/ant-design#21906

---

src/generate/moment.ts
src/utils/dateUtil.ts
tests/util.spec.tsx

Reverts react-component/picker#38

Revert "fix ant-design/ant-design#21906"

---

examples/basic.tsx
src/generate/moment.ts
src/utils/dateUtil.ts
tests/panel.spec.tsx

fix https://github.com/ant-design/ant-design/issues/21906

fix: moment set firstDayOfWeek issue

---

src/utils/uiUtil.ts

fix https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/20

chore: Update default format

---

src/RangePicker.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/22991

fix: RangePicker selection switch

---

src/Picker.tsx
tests/picker.spec.tsx

Ref: https://github.com/ant-design/ant-design/issues/22499

fix: add `autoComplete` support

---

src/Picker.tsx
tests/picker.spec.tsx

fix https://github.com/ant-design/ant-design/issues/23477

fix: Disabled should not click to open

---

src/RangePicker.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/23726

fix: Disabled RangePicker display issue

---

src/PickerPanel.tsx
tests/picker.spec.tsx

ref https://github.com/ant-design/ant-design/issues/24178

fix: DisabledDate should block today

---

src/locale/ga_IE.ts

added ga_IE (Irish) also updated in ant-design

Added Irish(ga_IE) locale

---

src/hooks/useRangeDisabled.ts
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/24840

fix: WeekPicker range disabled logic

---

src/Picker.tsx
src/RangePicker.tsx
src/hooks/useValueTexts.ts
tests/picker.spec.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/24934

fix: first  formats work

---

package.json
src/RangePicker.tsx
src/hooks/useRangeDisabled.ts
tests/range.spec.tsx

* start 选择完毕后，如果 end 不是 disabled 则自动弹出，同时禁用 start 之前的所有时间。
* end 选择完毕后，如果 start 不是 disabled 则自动弹出，同时禁用 end 之后的所有时间。

chore: Adjust close logic

---

.circleci/config.yml
src/RangePicker.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/25398

fix: RangePicker logic

---

src/generate/dayjs.ts

fix https://github.com/ant-design/ant-design/issues/25489

fix: hide warning while no formatText is given

---

package.json
src/generate/dateFns.ts
src/generate/dayjs.ts
tests/generate.spec.tsx

ref issue: https://github.com/ant-design/ant-design/issues/22732

feat: support date-fns

---

src/generate/dateFns.ts
tests/generate.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/25881

fix: date-fns format string compatible

---

src/RangePicker.tsx
tests/range.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/26188

fix: RangePicker should close when clear clicked

---

src/PickerPanel.tsx
tests/panel.spec.tsx
tests/range.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/26390

fix: RangePicker should keep disabled

---

src/RangePicker.tsx
tests/__snapshots__/picker.spec.tsx.snap
tests/__snapshots__/range.spec.tsx.snap
tests/range.spec.tsx

close [#26544](https://github.com/ant-design/ant-design/issues/26544)

fix: should clear hover style of input when selecting the same value

---

src/Picker.tsx
src/RangePicker.tsx
src/utils/dateUtil.ts
tests/picker.spec.tsx
tests/range.spec.tsx

之前只是禁止 input 输入，但是忘了清除的时候还是会走解析值的逻辑。

fix:  clear value when format is function

---

src/panels/TimePanel/TimeBody.tsx
tests/__snapshots__/panel.spec.tsx.snap
tests/panel.spec.tsx

resolve https://github.com/ant-design/ant-design/issues/25009

Fix disabled

---

src/panels/PanelBody.tsx

https://github.com/react-component/picker/pull/175
补充年份起始

feat: add year start & end

---

package.json

fix https://github.com/ant-design/ant-design/issues/26190#issuecomment-775397824

chore: use Day.js as peerDependencies

---

src/RangePicker.tsx
tests/range.spec.tsx

Fixes # Fix issue [Tooltip在TimePicker.RangePicker外面无效](https://github.com/ant-design/ant-design/issues/30893)

RangePicker support onMouseEnter、onMouseLeave

---

src/Picker.tsx

Reference taken from https://github.com/react-component/picker/blob/master/src/RangePicker.tsx#L589-L592
Fixes: ant-design/ant-design#31673

picker reopen on edge click fixes:ant-design/ant-design#31673

---

src/locale/ka_GE.ts

Added Georgian locale (ka_GE)
close #164

Add ka_GE locale

---

assets/index.less

fix: allow overriding of the color on cell hover

---

examples/range.tsx
src/RangePicker.tsx
tests/range.spec.tsx

Fix https://github.com/ant-design/ant-design/issues/31334

fix: rang-picker should not trigger on disabledDate by keyboard

---

src/panels/DatetimePanel/index.tsx
tests/panel.spec.tsx

Fix: https://github.com/ant-design/ant-design/issues/33583

fix: showTime.defaultValue should only works at first render

---

src/Picker.tsx
tests/__snapshots__/picker.spec.tsx.snap
tests/picker.spec.tsx

Feature: Added inputRender prop to have the ability to replace default input element with custom.

---

docs/examples/range.tsx
src/RangePicker.tsx
tests/range.spec.tsx

close https://github.com/ant-design/ant-design/issues/34755
close https://github.com/ant-design/ant-design/issues/34572﻿

fix: fix rangepicker panel position

---

docs/examples/rtl.tsx

- 修复 rlt 示例 RangePicker onChange 错误
- 设置 defaultValue 为当前时间

docs: fix rlt mode change range value error

---

src/locale/eu_ES.ts

Added Basque (eu-ES) Translation

Added Basque (eu-ES) Translation

---

docs/examples/range.tsx
src/RangePicker.tsx
src/hooks/usePickerInput.ts
tests/range.spec.tsx

- fix: https://github.com/ant-design/ant-design/issues/38350

fix: should not trigger blur event while picker's input focused

---

src/Picker.tsx
src/RangePicker.tsx
src/hooks/useValueTexts.ts
tests/picker.spec.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/39051

fix:  picker offset check

---

src/Picker.tsx
src/hooks/useTextValueMapping.ts

fix https://github.com/ant-design/ant-design/issues/38493

fix: flash of it

---

src/locale/my_MM.ts

ref: https://github.com/react-component/pagination/issues/517

fix: fix Burmese - MYANMAR locale typo

---

src/RangePicker.tsx

ref https://github.com/ant-design/ant-design/issues/42034

chore: delay of open with blur check

---

src/hooks/useRangeOpen.ts
tests/range.spec.tsx

fix: open no lock

---

src/hooks/useRangeDisabled.ts
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/42552

fix: panel shouldn't be clicked with open and disabled

---

src/locale/ne_NP.ts

file added src/locale/ne_NP.ts

Internationalization added for nepali language

---

src/Picker.tsx
src/RangePicker.tsx
src/utils/miscUtil.ts

https://github.com/ant-design/ant-design/issues/39900#issuecomment-1565596302

refactor: use rc-util/lib/pickAttrs

---

src/hooks/useTimeSelection.ts
src/hooks/useTimeWithDisabled.ts
src/panels/TimePanel/TimeBody.tsx
tests/disabledTime.spec.tsx

fix https://github.com/ant-design/ant-design/issues/42468

fix: dynamic disabledTime should be correct

---

src/panels/DecadePanel/DecadeBody.tsx
src/panels/DecadePanel/DecadeHeader.tsx
src/panels/DecadePanel/constant.ts
src/panels/DecadePanel/index.tsx
src/panels/YearPanel/YearBody.tsx
src/panels/YearPanel/YearHeader.tsx
src/panels/YearPanel/constant.ts
src/panels/YearPanel/index.tsx
src/utils/dateUtil.ts

https://github.com/ant-design/ant-design/pull/42750
node_modules/rc-picker/es/panels/DecadePanel/DecadeBody.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js -> node_modules/rc-picker/es/panels/DecadePanel/DecadeBody.js @kiner-tang 
node_modules/rc-picker/es/panels/DecadePanel/DecadeHeader.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js -> node_modules/rc-picker/es/panels/DecadePanel/DecadeHeader.js  @kiner-tang 
node_modules/rc-picker/es/panels/DecadePanel/index.js -> node_modules/rc-picker/es/panels/DecadePanel/DecadeHeader.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js  @kiner-tang 
node_modules/rc-picker/es/panels/PanelBody.js -> node_modules/rc-picker/es/utils/dateUtil.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js -> …

refactor: solve picker circular dependency issue

---

src/PickerPanel.tsx
tests/panel.spec.tsx

close https://github.com/ant-design/ant-design/issues/43354

fix: hide bottom button when switch date interval in the head

---

src/utils/dateUtil.ts
tests/panel.spec.tsx
tests/picker.spec.tsx
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/44107

fix: WeekPicker logic

---

src/hooks/useTimeSelection.ts
src/panels/TimePanel/TimeBody.tsx
tests/disabledTime.spec.tsx

fix antd 4.x https://github.com/ant-design/ant-design/issues/42468

fix: 2.7.x dynamic disabledTime should be correct

---

package.json

resolve https://github.com/ant-design/ant-design/issues/44708

chore: bump rc-util

---

src/Picker.tsx
src/interface.ts
src/panels/TimePanel/index.tsx
tests/disabledTime.spec.tsx

fix: delete redundant params

---

.gitignore
docs/examples/time.tsx
src/panels/DatetimePanel/index.tsx
tests/disabledTime.spec.tsx

fix https://github.com/ant-design/ant-design/issues/44289

fix: DatePicker 中disabledTime 禁用问题

---

src/RangePicker.tsx
src/hooks/useValueTexts.ts
tests/loop.spec.tsx

DayJs always trade InvalidateDate is not same. Add one more memo logic.

fix: DayJS loop trigger effect

---

src/utils/getClearIcon.tsx

type: update getClearIcon type

type: update getClearIcon type

---

package.json

chore(deps-dev): bump typescript from 4 to 5

chore(deps-dev): bump typescript from 4 to 5

---

package.json

chore(deps-dev): bump prettier from 2 to 3

chore(deps-dev): bump prettier from 2 to 3

---

src/hooks/useLocale.ts

type: update fillLocale return type

type: update fillLocale return type

---

package.json

chore(deps-dev): bump react & react-dom from 17 to 18

chore(deps-dev): bump react & react-dom from 17 to 18

---

docs/examples/debug.tsx
src/hooks/useTimeConfig.ts
src/hooks/useTimeInfo.ts
tests/panel.spec.tsx

fix: `showTime` align logic

---

docs/examples/debug.tsx
src/PickerPanel/index.tsx
tests/panel.spec.tsx

ref https://github.com/ant-design/ant-design/issues/47354

fix: PickerPanel controlled not sync internal pickerValue

---

docs/examples/debug.tsx
src/PickerInput/Popup/index.tsx
src/PickerInput/Selector/RangeSelector.tsx
tests/range.spec.tsx

这个修复对算法进行了调整，但是不会对容器圆角进行过滤，还需要到 antd 中进行修复。

fix: Arrow logic adjust

---

src/PickerInput/hooks/useRangePickerValue.ts
tests/picker.spec.tsx

fix https://github.com/ant-design/ant-design/issues/47511

fix: Picker maxDate limit switch pickerValue not correct

---

src/generate/dateFns.ts
tests/generate.spec.tsx

ref https://github.com/react-component/picker/pull/289#issuecomment-1063640635
close #147
close #289 
close ant-design/ant-design#47339
close ant-design/ant-design#47600

fix: DateFNS locale fallback mapping

---

src/Picker.tsx
tests/picker.spec.tsx

fix [#46669](https://github.com/ant-design/ant-design/issues/46669)

fix: unexpected trigger clear

---

assets/index.less
docs/examples/debug.tsx
src/PickerInput/Selector/SingleSelector/index.tsx
tests/multiple.spec.tsx

ref https://github.com/ant-design/ant-design/issues/47665

feat: multiple single picker show placeholder

---

src/PickerInput/Selector/SingleSelector/MultipleDates.tsx
src/PickerInput/Selector/SingleSelector/index.tsx

fix: dom order

---

docs/examples/debug.tsx
src/PickerInput/hooks/useDisabledBoundary.ts
src/PickerInput/hooks/useFilledProps.ts
tests/new-range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/48265

fix: min/maxDate should also blocked by typing

---

src/PickerInput/Selector/RangeSelector.tsx

https://github.com/ant-design/ant-design/pull/49333

fix: arrow position when placement is right

---

docs/examples/range.tsx
src/PickerInput/RangePicker.tsx
src/PickerInput/hooks/useRangeActive.ts
tests/range.spec.tsx

fix https://github.com/ant-design/ant-design/issues/49512

fix: field input focus switch trigger

---

src/generate/dateFns.ts
tests/keyboard.spec.tsx
tests/util/commonUtil.tsx

fix ant-design/ant-design#48509
fix #808

fix: dateFns wrong format when typing date

---

assets/index.less

配置 rc-picker-content direction 为 ltr

fix: rc-picker-content direction set ltr

---

src/PickerPanel/DatePanel/index.tsx

[antd#50157](https://github.com/ant-design/ant-design/issues/50157)
picker=week支持showWeek=false，允许隐藏周序号

fix: allow showWeek=false when picker=week (antd#50157)
