- examples/basic.tsx
- examples/rtl.tsx
- src/generate/moment.ts
- src/utils/uiUtil.ts
- tests/picker.spec.tsx
fix https://github.com/ant-design/ant-design/issues/20248
> fix: Week parse logic

- package.json
- src/RangePicker.tsx
- tests/range.spec.tsx
ref: https://github.com/ant-design/ant-design/pull/20736#issuecomment-572344743
> fix: rangePicker footer hide when empty

- src/PanelContext.tsx
- src/Picker.tsx
- src/PickerPanel.tsx
- tests/picker.spec.tsx
ref https://github.com/ant-design/ant-design/issues/21153
> fix: Add `defaultOpenValue` support

- src/Picker.tsx
- tests/__snapshots__/picker.spec.tsx.snap
当时间选择框比较短的时候加个title会有个更友好的交互，能看到选择到的时间。
> chore: more friendly tips

- src/RangePicker.tsx
- tests/range.spec.tsx
fix https://github.com/ant-design/ant-design/issues/21900
> fix: RangePicker should reorder when start is after end

- .prettierrc
- README.md
- src/RangePicker.tsx
- tests/range.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/21916
> feat: Time RangePicker support endTime before startTime

- examples/basic.tsx
- examples/panel.tsx
- src/PickerPanel.tsx
- src/interface.ts
- src/panels/QuarterPanel/QuarterBody.tsx
- src/panels/QuarterPanel/QuarterHeader.tsx
- src/panels/QuarterPanel/index.tsx
- src/utils/dateUtil.ts
- src/utils/uiUtil.ts
- tests/keyboard.spec.tsx
- tests/panel.spec.tsx
- tests/picker.spec.tsx
ref https://github.com/ant-design/ant-design/issues/22150
> feat: Quarter Picker

- src/generate/moment.ts
这个PR主要是修改了调用 moment API 时的写法，返回计算结果而不是其自身，更加贴近 immutable  的概念，也能让 https://www.npmjs.com/package/antd-dayjs-webpack-plugin 摆脱 badMutable 插件，真正实现 immutable
> feat: Update GenerateConfig to make it immutable

- src/Picker.tsx
- src/PickerPanel.tsx
- src/hooks/usePickerInput.ts
- tests/keyboard.spec.tsx
fix https://github.com/ant-design/ant-design/issues/23152
> Fix disabled

- src/Picker.tsx
- src/RangePicker.tsx
- tests/picker.spec.tsx
- tests/range.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/23727
> feat: `id` should work on Picker

- examples/basic.tsx
- src/Picker.tsx
ref: https://github.com/ant-design/ant-design/issues/23918
> fix: add `tabIndex` support

- .eslintrc.js
- src/RangePicker.tsx
- tests/picker.spec.tsx
- tests/range.spec.tsx
做成了一个 object 免得未来还有需要拓展。另外帮忙看一下名字：
```tsx
export type RangeDateRender<DateType> = (
currentDate: DateType,
today: DateType,
info: {
range: 'start' | 'end';
},
) => React.ReactNode;
```
`position` 在内部是双面板时区分左右用的，免得未来拓展搞迷糊就没用这个名字用了 `range`，帮忙看看有没有更好的命名。
ref: https://github.com/ant-design/ant-design/issues/24124#event-3349878879
> feat: RangePicker `dateRender` support additional info

- src/hooks/useRangeViewDates.ts
- tests/range.spec.tsx
Refs to https://github.com/ant-design/ant-design/issues/21084
Update `viewDates` when any item is selected. 
Whether this will cause other impacts, needs further review.
> fix: ant-design/ant-design#21084 improve range picker calendar display on select

- src/panels/MonthPanel/MonthHeader.tsx
- src/panels/QuarterPanel/QuarterHeader.tsx
- src/panels/YearPanel/YearHeader.tsx
relative issue: https://github.com/ant-design/ant-design/issues/24937
> fix: icons in month and quarter

- README.md
- src/RangePicker.tsx
- src/hooks/useTextValueMapping.ts
- tests/range.spec.tsx
- tests/setup.js
- tests/util/commonUtil.tsx
> 1. 选结束时间直接关闭浮层，完成选择。
> 2. 选开始时间会保持浮层，需要再点结束时间，这样和初始选择的习惯保持一致。
发现还有一些边界情况，调整为：
* 开始时间关闭，如果结束时间可以输入则打开结束时间。
* 结束时间关闭，如果开始时间为空则打开开始时间。
* 结束时间打开的开始时间，关闭后不打开结束时间
* 结束时间打开的开始时间，如果开始时间晚于结束时间，则重置结束时间，同时再次打开结束时间 
ref https://github.com/ant-design/ant-design/issues/25120
> chore: Adjust open picker logic

- src/Picker.tsx
- src/RangePicker.tsx
- src/hooks/usePickerInput.ts
- tests/range.spec.tsx
调整了一下逻辑。
如果用户在 RangePicker 里打开了面板但是没做其他操作，那么关闭面板时不会触发第二个面板的开启。
> chore: Not trigger switch when user do nothing on input

- src/hooks/usePickerInput.ts
Safari 版本13.1 (15609.1.20.111.8) 下。
https://picker.react-component.now.sh/?path=/story/rc-picker--basic
https://ant.design/components/date-picker/
点开 DatePicker 后，第一次选择日期大概率失效。
> fix: Safari cannot select date in first open

- src/Picker.tsx
- src/RangePicker.tsx
- src/generate/dayjs.ts
- src/hooks/useHoverPlaceholder.ts
- src/hooks/useValueTexts.ts
- tests/picker.spec.tsx
- tests/range.spec.tsx
[#25050](https://github.com/ant-design/ant-design/issues/25050)
@afc163 @zombieJ 
试试功能有没有问题，没问题晚上回去我把测试补上。
> feat: improve hovering experience

- src/RangePicker.tsx
- tests/range.spec.tsx
[#25746](https://github.com/ant-design/ant-design/issues/25746)
> 🐛 fix: disabledDate is not work when selecting time directly

- src/locale/lt_LT.ts
Im using antdesign and they have dependencies to picker version ~1.15.1 but there was no lithuanian language.
> added lithuanian language

- examples/switchType.tsx
- src/PickerPanel.tsx
- tests/picker.spec.tsx
when `picker` prop is changed, rendered panel won't be changed.
https://ant.design/components/date-picker-cn/#components-date-picker-demo-switchable
> fix: picker change won't change panel

- src/RangePicker.tsx
- tests/range.spec.tsx
[#26024](https://github.com/ant-design/ant-design/issues/26024)
@afc163 @zombieJ
> fix(range): panel keep open when nextValue is empty(#26024)

- examples/range.tsx
- src/PickerPanel.tsx
- tests/keyboard.spec.tsx
fix https://github.com/ant-design/ant-design/issues/25403
> fix: RangePicker arrow keys do not start from current date

- src/generate/dateFns.ts
- tests/generate.spec.tsx
Currently the weekdays and months is disappear on picker when using the `dateFns` generate config.
This PR implement `getShortWeekDays` and `getShortMonths` in dateFns generate config to fixed it, otherwise we need define `shortMonths` and `shortWeekDays` in locale files.
> fix: missing week days and months when using dateFns generate config

- src/RangePicker.tsx
- src/hooks/useHoverValue.ts
- tests/picker.spec.tsx
- tests/range.spec.tsx
> chore: optimize hover value experience

- src/Picker.tsx
- src/RangePicker.tsx
- src/hooks/useValueTexts.ts
- src/interface.ts
- src/utils/dateUtil.ts
- src/utils/uiUtil.ts
- tests/picker.spec.tsx
- tests/range.spec.tsx
close [#17222](https://github.com/ant-design/ant-design/issues/17222)
> feat: supprt custom format

- src/RangePicker.tsx
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/23167
用户在面板中选择的时候，如果没有选择日期直接选择时间，之前默认取的日期是当前日期，会存在当前日期被禁用，小于开始日期等情况。
现在改为了选择结束日期的时候，默认值为开始日期，反之亦然。
> chore(range): panel defaultValue should be relative to startDate/endDate

- src/RangePicker.tsx
- src/panels/DatePanel/DateBody.tsx
- src/panels/DatePanel/DateHeader.tsx
- src/panels/MonthPanel/MonthBody.tsx
- src/panels/MonthPanel/MonthHeader.tsx
- src/panels/QuarterPanel/QuarterBody.tsx
- src/panels/QuarterPanel/QuarterHeader.tsx
- src/panels/TimePanel/TimeHeader.tsx
- src/panels/YearPanel/YearBody.tsx
格式化值统一使用 `formatValue` 方法，防止有的 format 是函数，然后报错(https://github.com/ant-design/ant-design/issues/27155)。
> chore: optimize format value

- src/generate/dateFns.ts
- src/generate/dayjs.ts
- src/generate/index.ts
- src/generate/moment.ts
- src/panels/PanelBody.tsx
- src/utils/timeUtil.ts
- tests/__snapshots__/panel.spec.tsx.snap
- tests/generate.spec.tsx
- tests/util.spec.tsx
https://github.com/ant-design/ant-design/issues/27798
月初 月末 加了额外的 className
> feat: add start end

- src/generate/dateFns.ts
- src/generate/dayjs.ts
- src/generate/index.ts
- src/generate/moment.ts
- src/hooks/useRangeDisabled.ts
- tests/generate.spec.tsx
Resolve [#27879](https://github.com/ant-design/ant-design/issues/27879)
When you click `2020-12-27 ~ 2020-12-31` these days to select `2021 - 1st` as end week, all the weeks before are disabled.
Previously, we use `weekNumber` for comparison, it works well in most cases. But when you click these days e.g. `2020-12-30`, it will return `202001`, which is smaller than the weeks before in 2020, and result in these weeks are disabled.
```js
// en-us
function weekNumber(date: DateType) { // 2020-12-30
const year = generateConfig.getYear(date); // 2020
const week = generateConfig.locale.getWeek(locale.locale, date); // 1
return year * 100 + week; // 202001
}
const disabled = weekNumber(date) > weekNumber(endDate);
```
Before:
After:
> fix: week range disabled rule

- examples/calendar.less
- examples/calendar.tsx
- src/Picker.tsx
- src/PickerPanel.tsx
- tests/keyboard.spec.tsx
- tests/setup.js
resolve https://github.com/ant-design/ant-design/issues/28004
> fix: Calendar should not trigger `onChange` when date is `disabled`

- src/panels/TimePanel/TimeBody.tsx
Right now the date disabled fields do not get updated when "PM" is clicked. 
This is because the hour memo does not have isPM as a dependency and never reconfigures the new options.
resolve ant-design/ant-design#25009
> Fixing use12hours not updating when PM is clicked.

- src/locale/ru_RU.ts
Renamed `locale.ok` key from English 'Ok' to Russian 'ОК' to be the same as in antd's ru_RU locale file ([for example](https://github.com/ant-design/ant-design/blob/master/components/locale/ru_RU.tsx#L37))
> fix: updated ru_RU locale

- src/hooks/usePickerInput.ts
- src/utils/uiUtil.ts
fix event.target if event triggered in shadow dom
> fix: fix picker in shadowdom

- examples/basic.tsx
- src/PickerPanel.tsx
- src/hooks/useHoverValue.ts
- src/panels/DatetimePanel/index.tsx
- src/utils/timeUtil.ts
close https://github.com/ant-design/ant-design/issues/29412
在 basic 那个例子的 Uncontrolled DateTime 查看效果
> chore: optimize experience of hover value

- src/locale/fr_CA.ts
Add French(Canada) fr_CA locale
> Feature:Add French(Canada) fr_CA locale

- src/locale/pt_BR.ts
Update the name of the days of the week and months for Brazilian Portuguese, as names in English are currently being displayed
> Fix: Update pt_BR.ts

- src/Picker.tsx
- tests/__snapshots__/picker.spec.tsx.snap
fix https://github.com/ant-design/ant-design/issues/30496
> chore: add role to clear button

- src/locale/ur_PK.ts
Adding new language Urdu locale for antd
> feat: add urdu locale

- package.json
1. Move dayjs out of peerDependencies
https://github.com/ant-design/ant-design/issues/31096
https://github.com/ant-design/ant-design/issues/23435
2. Use wide semver version range for dayjs and date-fns , avoid https://github.com/ant-design/ant-design/issues/26190#issuecomment-775397824
> fix: dayjs and date-fns as deps with wide semver version range

- src/RangePicker.tsx
This is fix for issue mentioned here:
https://github.com/ant-design/ant-design/issues/30810
> fixed DatePicker will reopen when click non input area

- src/PickerPanel.tsx
- src/RangePicker.tsx
- tests/range.spec.tsx
I am trying to fix [this Bug ](https://github.com/ant-design/ant-design/issues/30005) I also ran into on the Ant Design range picker.
> fix: RangePicker.defaultPickerValue has no effect if showTime is set

- src/locale/es_MX.ts
Add support for es_MX locale
This is needed because I'm trying to add support for es_MX to https://github.com/ant-design/ant-design and I need to import that locale from this repo as well
> Add es_MX locale

- README.md
- assets/index.less
- docs/demo/time.md
- docs/examples/time.tsx
- src/Picker.tsx
- src/RangePicker.tsx
- src/panels/DatetimePanel/index.tsx
- src/panels/TimePanel/TimeBody.tsx
- src/panels/TimePanel/index.tsx
- src/utils/warnUtil.ts
- tests/disabledTime.spec.tsx
- tests/range.spec.tsx
ref https://github.com/ant-design/ant-design/issues/33425
> feat: Support disabledTime on TimePicker

- src/RangePicker.tsx
- tests/range.spec.tsx
Fix ant-design bug
https://github.com/ant-design/ant-design/issues/33662
> fix:Range onClick event not working

- src/locale/pt_PT.ts
Adds missing translation for shortWeekDays and shortMonths, in portuguese (ptPT).
> Add `shortWeekDays` and `shortMonths` to pt_PT.ts

- src/locale/si_LK.ts
භාෂාවේ නම: Sinhalese / Sinhala
දේශීය නම: සිංහල
කේතය: සිං / si
`si_LK` is unnecessary but it seems we cannot use `si`
> නව භාෂාවක් එකතු කිරීම

- src/PickerPanel.tsx
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/36154
close https://github.com/ant-design/ant-design/issues/21811
close https://github.com/react-component/picker/issues/421
> fix: RangePicker `date.month is not a function` error

- src/locale/uz_UZ.ts
It was added Uzbek language (uz_UZ)
> feat: add Uzbek language (uz_UZ)

- docs/examples/range.tsx
- src/RangePicker.tsx
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/36507
> fix: panel flick in some edge case

- src/Picker.tsx
- tests/picker.spec.tsx
fix https://github.com/ant-design/ant-design/issues/37165
> fix: Picker should open when click inside

- src/generate/dayjs.ts
- tests/generate.spec.tsx
https://github.com/react-component/picker/issues/482
https://github.com/ant-design/ant-design/issues/38839
> fix(generate): `dayjs` default strict mode

- src/RangePicker.tsx
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/40906
在都被禁用的情况下会使用默认值，但是在单个被禁用的情况下由于传入空数组导致被重新赋值，因此判断如果存在传入值那么就不再进行重新赋值。
> fix: Use the passed in default when disabled

- package.json
In [the PR](https://github.com/react-component/picker/pull/230) adding the luxon integration, the peer dependencies were not updated properly.
The PR was open for quite some time and the project structure evolved in the meantime, I forgot to adjust this part on the latest rebase.
Simply adding the missing dependencies.
> fix: add missing luxon peer dependency

- src/PickerPanel.tsx
- src/RangePicker.tsx
- tests/panel.spec.tsx
- fix https://github.com/ant-design/ant-design/issues/41751
> fix: resolve deprecated warning display unexpected issue

- src/PickerPanel.tsx
- tests/keyboard.spec.tsx
close https://github.com/ant-design/ant-design/issues/41677
在之前 antd 的 Calendar 中可用通过键盘访问到 disabledDate 并触发 select 事件，因此这里监听键盘事件，来判断要前往到日期是否为 disabledDate，如果是则不会触发键盘事件。
> fix: Able to navigate between disabled dates with keyboard

- tests/picker.spec.tsx
- tests/range.spec.tsx
enzyme 已经荒了，有些和 jsdom 的检查会直接卡死，只能 skip 掉了。最好的方式是把测试转成 testing lib，但是这个性价比有点太低了。
> test: Fix CI

- src/hooks/usePickerInput.ts
- tests/picker.spec.tsx
fix https://github.com/ant-design/ant-design/issues/41608
Picker will not fire `onBlur` if clicking within its elements and it is in focus, although the input element inside may blur.
> fix: prevent picker blur when still in focus

- src/hooks/usePickerInput.ts
- tests/picker.spec.tsx
fix https://github.com/ant-design/ant-design/issues/41608
ref https://github.com/react-component/picker/pull/612
> fix: prevent picker blur when still in focus at 2.7.x

- src/RangePicker.tsx
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/41579
> chore: Duplicate `Use the passed in default when disabled`

- docs/examples/basic.tsx
- docs/examples/range.tsx
- package.json
- src/Picker.tsx
- src/RangePicker.tsx
- src/hooks/usePickerInput.ts
- src/hooks/useRangeDisabled.ts
- src/hooks/useRangeOpen.ts
- tests/blur.spec.tsx
- tests/picker.spec.tsx
- tests/range.spec.tsx
ref https://github.com/ant-design/ant-design/issues/42034
> feat: support `changeOnBlur`

- src/RangePicker.tsx
In some test env. Developer hack `@rc-component/trigger` to force open for testing snapshot. Here is to ensure keep snapshot same as before.
Note: this will never reach for real world.
> chore: compatible with antd test

- src/RangePicker.tsx
- tests/__snapshots__/range.spec.tsx.snap
- tests/range.spec.tsx
- fix https://github.com/ant-design/ant-design/issues/42493
close #637
> fix: disabled panel still open when finish choose and next is disabled

- src/RangePicker.tsx
When evaluating `arrowRef.current.offsetLeft`, maybe `arrowRef.current` is null. As a result it throws `undefined is not an object` error.
So I add a null check before.
@zombieJ 
close https://github.com/ant-design/ant-design/issues/42849
> fix: add null check of arrowRef.current

- docs/examples/basic.tsx
- docs/examples/range.tsx
- src/PresetPanel.tsx
- src/hooks/usePresets.ts
- src/interface.ts
- src/utils/miscUtil.ts
- tests/picker.spec.tsx
- tests/range.spec.tsx
background: ant-design/ant-design/issues/43203
> feat: preset value support callback function

- src/RangePicker.tsx
- src/hooks/useRangeOpen.ts
- tests/range.spec.tsx
fix https://github.com/ant-design/ant-design/issues/43512
> fix: should not action when RangePicker set disabled

- src/hooks/useRangeOpen.ts
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/43802
> fix: fix panel not switch when select date with open is true

- docs/demo/locale.md
- docs/examples/locale.tsx
- src/hooks/useValueTexts.ts
- tests/picker.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/44337
`rc-picker` 本身其实无法感知日期库的变化，但是我们可以利用 `locale` 做一下对比。如果 `locale` prop 变了，那么就假定对应的日期库语言也变了。
> fix: picker locale trigger

- src/hooks/useTimeSelection.ts
- tests/disabledTime.spec.tsx
- tests/picker.spec.tsx
close https://github.com/ant-design/ant-design/issues/44524
使 datetime 模式在不选择日期，直接选择分、秒的情况下自动应用当前时间的时、分。
> improvement: dateTime mode apply the current time

- src/RangePicker.tsx
- src/hooks/usePickerInput.ts
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/44280
问题出现原因：
在设置了 showTime 和 changeOnBlur 后，在没有点击确认按钮时点击输入框切换选择开始或结束日期时不会触发对应的 onChange 事件，因此 disabledDate 就失效了，导致最终可以选择出不符合 disabledDate 的时间范围。
解决思路：
去触发切换前输入框的 `onCalendarChange` 事件。
ref: 
https://github.com/ant-design/ant-design/issues/24704
https://github.com/ant-design/ant-design/issues/30467
https://github.com/ant-design/ant-design/issues/31261
> fix: dateTime mode switch should trigger onCalendarChange

- src/Picker.tsx
- src/RangePicker.tsx
- src/hooks/usePickerInput.ts
- tests/range.spec.tsx
发现两个问题：
1、之前当 showTime 和 changeOnBlur 同时存在时，会先执行 changeOnBlur 对应的事件，但是因为取值逻辑的关系无法获取到正确的 value，导致不会触发后续的 onCalendarChange；
2、showTime 和 changeOnBlur 同时存在时，当切换输入框就会关闭时间选择面板。
ref: https://github.com/ant-design/ant-design/issues/44280
> fix: resolves an issue that occurs when showTime and changeOnBlur exist at the same time

- src/RangePicker.tsx
- src/hooks/useRangeOpen.ts
- tests/range.spec.tsx
close https://github.com/ant-design/ant-design/issues/44992
> fix: unable to close the panel use the confirm button

- src/hooks/useTimeSelection.ts
- tests/picker.spec.tsx
Fix `disabledTime.disabledMinutes`, `disabledTime.disabledSeconds` hour argument for 12 hours picker format
Before: 
https://github.com/react-component/picker/assets/70964765/2001c123-90a2-41dc-a10f-57ddb4f4db83
After:
https://github.com/react-component/picker/assets/70964765/bcd1ce7e-e1a1-4604-bb25-baa122d428ea
> fix: fix 12 hours format incorrect hour pass

- src/panels/DatetimePanel/index.tsx
- tests/disabledTime.spec.tsx
ref: #666
fix https://github.com/ant-design/ant-design/issues/44289 again.
> fix: fix disabledTime not working when there is no default value

- src/PickerPanel/PanelHeader.tsx
- src/PickerPanel/context.ts
- src/PickerPanel/index.tsx
- tests/internal.spec.tsx
> feat: add hideHeader

- docs/examples/debug.tsx
- tests/keyboard.spec.tsx
close https://github.com/react-component/picker/security/code-scanning/180
close https://github.com/react-component/picker/security/code-scanning/181
close https://github.com/react-component/picker/security/code-scanning/182
close https://github.com/react-component/picker/security/code-scanning/183
close https://github.com/react-component/picker/security/code-scanning/184
> fix: Unused variable, import, function or class

- src/PickerInput/Popup/PopupPanel.tsx
- src/PickerInput/RangePicker.tsx
- src/PickerInput/hooks/useFilledProps.ts
- tests/new-range.spec.tsx
fix https://github.com/ant-design/ant-design/issues/47492
> fix: RangePicker double click should only act on needConfirm case

- docs/examples/debug.tsx
- src/PickerPanel/TimePanel/TimePanelBody/index.tsx
- tests/new-range.spec.tsx
- tsconfig.json
fix https://github.com/ant-design/ant-design/issues/47682
> fix: RangePicker switch field should keep the time sync with date

- src/PickerInput/RangePicker.tsx
related to https://github.com/react-component/picker/pull/758
In that PR, I tried to update the behavior when users clear values on `RangePicker` because the value is not fit to its type.
It is actually by design. ([see](https://github.com/react-component/picker/pull/758#issuecomment-1965676604))
However, the problem I mentioned in https://github.com/react-component/picker/issues/757 is not fixed yet.
In this PR, I update the type to solve it.
> fix the first argument type of `onChange` of the `RangePicker`.

- src/locale/ko_KR.ts
> fix: locale ko-KR uses dayFormat 'D' instead of 'Do'

- docs/examples/debug.tsx
- docs/examples/multiple.tsx
- src/PickerInput/hooks/useFilledProps.ts
- src/hooks/useTimeConfig.ts
- tests/new-range.spec.tsx
- tests/range.spec.tsx
- tests/time.spec.tsx
- tsconfig.json
fix https://github.com/ant-design/ant-design/issues/47549
处理逻辑：
* 都没有定义时，优先根据 format 来，反之为 true
* 存在 false 时，默认为 true
* 存在 true 时，默认为 false
* 都存在时，默认为 true
> fix: showXXX=false will make others as true

- docs/examples/debug.tsx
- src/PickerInput/Popup/Footer.tsx
- src/PickerInput/Popup/index.tsx
- src/PickerInput/RangePicker.tsx
- src/PickerInput/hooks/useInvalidate.ts
- src/PickerInput/hooks/useRangeDisabledDate.ts
- src/PickerTrigger/util.ts
- src/interface.tsx
- src/utils/miscUtil.ts
- tests/new-range.spec.tsx
ref https://github.com/ant-design/ant-design/issues/48594
> feat: Picker `disabledTime` support `info.form`

- assets/index.less
- src/PickerInput/Popup/index.tsx
- src/PickerInput/RangePicker.tsx
- src/PickerInput/Selector/RangeSelector.tsx
- tests/__snapshots__/range.spec.tsx.snap
- tests/range.spec.tsx
Close https://github.com/ant-design/ant-design/issues/47699
> fix: placement right

- src/locale/tr_TR.ts
Hi there,
I have added short names for week days and months for calendar.
Also, updated the date and date time format to be more convenient in Turkish.
> Fix locale date formats and short names in Turkish language

- docs/examples/modes.tsx
- src/PickerInput/hooks/useRangePickerValue.ts
- tests/keyboard.spec.tsx
- tests/picker.spec.tsx
close https://github.com/ant-design/ant-design/issues/49400
> fix: RangePicker throws error when input end value first

- src/PickerInput/RangePicker.tsx
- tests/range.spec.tsx
Added `flushSubmit` call to `onSelectorBlur`
Fixes the issue: https://github.com/ant-design/ant-design/issues/49057
> fix: range picker saves only last changed date

- src/generate/dateFns.ts
Date-fns can work win number or Date by default.  It is ok, when config work as expected using date-fns lib
> dateFnsGenerateConfig: pass all getters through date-fns

- src/PickerInput/Popup/index.tsx
- src/PickerInput/RangePicker.tsx
- tests/new-range.spec.tsx
输入框 blur 的时候是否触发 change 需要前置判断一下是用户自己手工输入了日期后 blur 还是操作了面板导致的 blur。
fix https://github.com/ant-design/ant-design/issues/49706
> fix: blur to trigger change

- src/PickerPanel/YearPanel/index.tsx
- tests/panel.spec.tsx
修改YearPanel的endDate为一年的最后一天，以及单词的错误拼写
> fix: 修改disableDate属性在YearPanel的错误视图

- src/PickerPanel/TimePanel/TimePanelBody/TimeColumn.tsx
- src/PickerPanel/TimePanel/TimePanelBody/index.tsx
- tests/time.spec.tsx
ref https://github.com/ant-design/ant-design/issues/50288
> enhance: opt picker time panel hover to show as placeholder

- src/PickerInput/RangePicker.tsx
- tests/range.spec.tsx
- tests/util/commonUtil.tsx
`DatePicker.RangePicker` 在 shadow dom 下没法选中 end date，组件在 shadow dom 下，通过 document.activeElement 只能拿到 shadow host
fix https://github.com/ant-design/ant-design/issues/50284
> fix: cannot select end time in shadow dom

- src/generate/luxon.ts
Luxon uses lowercase `a` for the meridiam token. Currently, AM/PM labels show up as `A` as Luxon passes it through
> fix: Luxon AM/PM formatting

- src/PickerInput/Selector/RangeSelector.tsx
- src/PickerInput/Selector/SingleSelector/index.tsx
- tests/new-range.spec.tsx
- tests/picker.spec.tsx
- tests/range.spec.tsx
I've created this pull request to fix https://github.com/ant-design/ant-design/issues/48059
> fix: add tabIndex support

- src/PickerInput/hooks/useRangeValue.ts
* fix: value is not work when set to null
* fix: innerValue only judge null
(cherry picked from commit 6bc9cb4e986f53c915ff1623cd195728d41b88d3)
#	src/PickerInput/hooks/useRangeValue.ts
> fix: value is not work when set to null (pick of #913)

- src/PickerInput/hooks/useRangeValue.ts
Reverts react-component/picker#913
ref https://github.com/react-component/picker/issues/912#issuecomment-2754328331
> Revert "fix: value is not work when set to null"
